"""
Keywords and hashtags for scraping
"""

KEYWORDS = {
    "aborto": "#aborto",
    "feminismo": "#feminismo",
    "misoprostol": "#misoprostol",
    "feminicidio": "#feminicidio",
    "niunamenos": "#niunamenos",
    "derechosreproductivos": "#derechosreproductivos",
    "interrupciondelembarazo": "#interrupciondelembarazo",
    "ile": "#ile",
    "ive": "#ive",
    "8m": "#8m",
    "mareaverde": "#mareaverde",
    "pañuelverde": "#pañuelverde",
    "abortolegal": "#abortolegal",
    "abortolibre": "#abortolibre",
    "decidireslibertad": "#decidireslibertad",
    "derechoadecidir": "#derechoadecidir",
    "educacionsexual": "#educacionsexual",
    "violenciaobstetrica": "#violenciaobstetrica",
    "planificacionfamiliar": "#planificacionfamiliar",
    "saludreproductiva": "#saludreproductiva",
    "cytotec": "#cytotec",
    "abortoseguro": "#abortoseguro",
    "machismosmata": "#machismosmata",
    "alertadegenero": "#alertadegenero",
    "violenciadefamilia": "#violenciadefamilia",
    "mareafeminista": "#mareafeminista",
    "pildoradeldiadespues": "#pildoradeldiadespues",
    "saludmenstrual": "#saludmenstrual",
    "patriarcado": "#patriarcado",
    "saludsexual": "#saludsexual",
    "nomasviolenciavicaria": "#nomasviolenciavicaria",
    "conlasinfanciasno": "#conlasinfanciasno",
    "leyvicaria": "#leyvicaria",
    "fncvv": "#fncvv",
    "violenciadigital": "#violenciadigital",
    "sexualidadlibre": "#sexualidadlibre",
    "perspectivadegenero": "#perspectivadegenero",
    "mujeresenstem": "#mujeresenstem",
    "mareaverdemx": "#mareaverdemx",
    "trans": "#trans",
    "pagalapension": "#pagalapension",
    "vivasnosqueremos": "#vivasnosqueremos",
    "justiciareproductiva": "#justiciareproductiva"
}

# Control group keywords
KEYWORDS_CONTROL = {
    "energiamasculina": "#energiamasculina",
    "energiafemenina": "#energiafemenina",
    "masculinidadtoxica": "#masculinidadtoxica",
    "redpill": "#redpill",
    "mgtow": "#mgtow",
    "alfamacho": "#alfamacho",
    "tradwife": "#tradwife",
    "feminidad": "#feminidad",
    "altovalor": "#altovalor",
    "eltemach": "#eltemach",
    "tradicionalfamily": "#tradicionalfamily",
    "valorestradicionales": "#valorestradicionales",
    "feminismotoxica": "#feminismotoxica",
    "ideologiadgenero": "#ideologiadgenero",
    "defenderlafamilia": "#defenderlafamilia",
    "vidadesdeelconcepto": "#vidadesdeelconcepto",
    "provida": "#provida",
    "machosalfa": "#machosalfa",
    "antiabortista": "#antiabortista",
}
